# Generated by Django 2.2.6 on 2019-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Use format YYYY for years so 2019 instead of just 19')),
                ('startdate', models.DateField(help_text="Use the first day of the conference as start date, at MUNOL it's usually Monday")),
                ('enddate', models.DateField(help_text='Last day of the conference, at MUNOL usually Saturday')),
                ('annual_session', models.PositiveSmallIntegerField(help_text='First session was in 1998, i.e. MUNOL 2020 will be the 23rd session')),
                ('theme', models.CharField(blank=True, help_text='Overarching topic of the conference', max_length=100)),
                ('pre_registration_deadline', models.DateTimeField()),
                ('final_registration_deadline', models.DateTimeField(blank=True)),
                ('position_paper_deadline', models.DateTimeField(blank=True)),
                ('chairhuman', models.CharField(help_text='Full name of the Chairman/woman of the MUNOL Association', max_length=50)),
                ('vice_chairhuman', models.CharField(help_text='Full name of the Vice-Chairman/woman of the MUNOL Association', max_length=50)),
                ('treasurer', models.CharField(help_text='Full name of the Treasurer of the MUNOL Association', max_length=50)),
                ('vice_treasurer', models.CharField(help_text='Full name of the Vice-Treasurer of the MUNOL Association', max_length=50)),
            ],
        ),
    ]
