# Generated by Django 2.2.6 on 2019-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='annual_session',
            field=models.PositiveSmallIntegerField(help_text='First session was in 1998, i.e. MUNOL 2020 will be the 23rd session', verbose_name='annual session'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='chairhuman',
            field=models.CharField(help_text='Full name of the Chairman/woman of the MUNOL Association', max_length=50, verbose_name='Chair:wo:man'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='enddate',
            field=models.DateField(help_text='Last day of the conference, at MUNOL usually Saturday', verbose_name='last day'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='final_registration_deadline',
            field=models.DateTimeField(blank=True, verbose_name='final registration deadline'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='position_paper_deadline',
            field=models.DateTimeField(blank=True, verbose_name='position paper deadline'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='pre_registration_deadline',
            field=models.DateTimeField(verbose_name='pre-registration deadline'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='startdate',
            field=models.DateField(help_text="Use the first day of the conference as start date, at MUNOL it's usually Monday", verbose_name='first day'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='theme',
            field=models.CharField(blank=True, help_text='Overarching topic of the conference', max_length=100, verbose_name='conference theme'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='treasurer',
            field=models.CharField(help_text='Full name of the Treasurer of the MUNOL Association', max_length=50, verbose_name='Treasurer'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='vice_chairhuman',
            field=models.CharField(help_text='Full name of the Vice-Chairman/woman of the MUNOL Association', max_length=50, verbose_name='Vice-Chair:wo:man'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='vice_treasurer',
            field=models.CharField(help_text='Full name of the Vice-Treasurer of the MUNOL Association', max_length=50, verbose_name='Vice-Treasurer'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Use format YYYY for years so 2019 instead of just 19', verbose_name='year of the conference'),
        ),
    ]
