# Generated by Django 2.2.6 on 2019-10-05 18:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191005_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Including second names if wanted', max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(help_text="Including prefixes like 'von', 'zu', 'de' etc.", max_length=50, verbose_name='last name')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], default='f', help_text="the diversity of genders is reflected in the 'other' choice", max_length=1, verbose_name='gender')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='remember to include the country code, e.g. for Germany +49 and then leave out the leading 0', max_length=128, region=None, verbose_name='mobile phone')),
                ('diet', models.CharField(choices=[('meat', 'meat'), ('vegetarian', 'vegetarian'), ('vegan', 'vegan')], default='vegetarian', help_text='main diet, smaller variations like allergies shall be indicated in the extras field', max_length=10, verbose_name='diet')),
                ('birthday', models.DateField(verbose_name='brithday')),
                ('extras', models.TextField(blank=True, help_text='please include here all additional information about diet, allergies, preferences etc. so that we can try to provide a perfect conference', verbose_name='extra information')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
