# Generated by Django 2.2.6 on 2019-10-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Participant')),
                ('ambassador', models.BooleanField(default=False, help_text='one delegate per delegation has to be selected to be the ambassador of the delegation', verbose_name="Is the delegate the delegation's ambassador?")),
            ],
            options={
                'abstract': False,
            },
            bases=('api.participant',),
        ),
    ]
