# Generated by Django 2.2.6 on 2019-10-05 18:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delegate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MUNDirector',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Participant')),
                ('landline_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="in case that a call is quicker than an email, don't forget the country code", max_length=128, region=None, verbose_name='landline phone')),
                ('english_teacher', models.BooleanField(default=True, help_text='English teachers can help with correcting the language and grammar of resolutions.', verbose_name='Is the MUN-Director an English teacher?')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.participant',),
        ),
        migrations.CreateModel(
            name='StudentOfficer',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Participant')),
                ('position_name', models.CharField(help_text="e.g. Chairman, Chairwoman, President, ... but <b>NOT</b> the entire title like 'Vice-Chairman of the First Committee' this will be generated automatically", max_length=20, verbose_name='Position name')),
                ('position_level', models.BooleanField(default=False, help_text='Main Student Officers might have other duties and obligations than vice/deputy Student Officers', verbose_name='Is this the main Student Officer of the forum?')),
                ('school_name', models.CharField(help_text='Name of the school/institution the student officer attends.', max_length=50, verbose_name='School name')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.participant',),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
    ]
