# Generated by Django 2.2.6 on 2019-10-05 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191005_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Participant')),
                ('position_name', models.CharField(help_text="e.g. 'Assistant Head of School Management'", max_length=50, verbose_name='Position name')),
                ('position_level', models.BooleanField(default=False, help_text='Main Head might have other duties and obligations than Assistant Heads', verbose_name='Is this the Head of this position?')),
                ('department_name', models.CharField(help_text="e.g. 'School Management', note that this name is <b>not</b> the entire position title", max_length=50, verbose_name='Department name')),
                ('school_name', models.CharField(default='Thomas-Mann-Schule', help_text='Name of the school/institution the Executive attends.', max_length=50, verbose_name='School name')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.participant',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Participant')),
                ('position_name', models.CharField(help_text="e.g. 'Administration Staff' or 'IT Staff'", max_length=50, verbose_name='Position name')),
                ('school_name', models.CharField(default='Thomas-Mann-Schule', help_text='Name of the school/institution the Staff member attends.', max_length=50, verbose_name='School name')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.participant',),
        ),
        migrations.AlterModelOptions(
            name='mundirector',
            options={'verbose_name': 'MUN-Director'},
        ),
        migrations.AlterModelOptions(
            name='studentofficer',
            options={'verbose_name': 'Student Officer'},
        ),
    ]
