# Generated by Django 2.2.6 on 2019-10-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191005_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Use common (short) version of the name, e.g. 'Russia' instead of 'Russion Federation' or 'EU' instrad of 'European Union', so use abbreviations. This name is only used internally and thus allows to create Countries twice, e.g. China 1 and China 2 if the delegation is split between two schools.", max_length=50, verbose_name="Member state's or Organization's name")),
                ('official_name', models.CharField(help_text="Official name as stated on resolutions of the UN, e.g. 'Russion Federation' instead of Russia. No abbreviations allowed here.", max_length=150, verbose_name='Official Name')),
                ('placard_name', models.CharField(help_text='The best readable compromise between no abbreviation but also not the full official name', max_length=50, verbose_name='Placards Name')),
                ('status', models.CharField(choices=[('member state', 'member state'), ('observer state', 'observer state'), ('former member state', 'former member state'), ('non-governmental organization', 'non-governmental organization'), ('inter-governmental organization', 'inter-governmental organization'), ('UN sub-body', 'UN sub-body')], default='member state', max_length=50, verbose_name='Status in the UN')),
                ('active', models.BooleanField(default=False, help_text='This allows to store all countries but only select the ones to be simulated and quickly change the selection.', verbose_name='Represented at this conference?')),
            ],
            options={
                'verbose_name': 'Member Organization',
            },
        ),
    ]
