# Generated by Django 2.2.6 on 2019-10-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_memberorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='represents',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='api.MemberOrganization'),
            preserve_default=False,
        ),
    ]
