# Generated by Django 2.2.6 on 2019-10-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191006_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='forum',
            field=models.ForeignKey(default='0', help_text='Select which forum this Delegate is a member of', on_delete=django.db.models.deletion.PROTECT, to='api.Forum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentofficer',
            name='forum',
            field=models.ForeignKey(blank=True, help_text='Select which forum this Student Officer is chairing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Forum'),
        ),
    ]
