# Generated by Django 2.2.6 on 2019-10-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191006_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Thomas-Mann-Schule'", max_length=100, verbose_name='Location name')),
                ('latitude', models.DecimalField(decimal_places=2, help_text='e.g. XX.XXXXXXXX', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=2, help_text='e.g. XX.XXXXXXXX', max_digits=10, verbose_name='Longitude')),
                ('zoom_level', models.PositiveSmallIntegerField(help_text='a number between 1 and 20, like google maps zoom levels', verbose_name='Zoom level')),
                ('address', models.CharField(help_text="e.g. 'Thomas-Mann-Straße 14', i.e. Streetname and House Number", max_length=100, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Location')),
                ('room_number', models.CharField(help_text="e.g. '0.23'", max_length=10, verbose_name='Room Number')),
                ('floor', models.PositiveSmallIntegerField(help_text='Ground Floor is level 0, First Floor is 1, etc.', verbose_name='Floor')),
            ],
            bases=('api.location',),
        ),
        migrations.AddField(
            model_name='forum',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Select a Room within the conference venue', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Room'),
        ),
    ]
