# Generated by Django 2.2.6 on 2019-10-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191006_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Event')),
            ],
            bases=('api.event',),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official Issue title as on the Agenda', max_length=256, verbose_name='Issue name')),
                ('forum', models.ForeignKey(help_text='Select the forum in which this issue is debated', on_delete=django.db.models.deletion.PROTECT, to='api.Forum')),
            ],
        ),
    ]
