# Generated by Django 2.2.6 on 2019-10-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191006_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='0', help_text='Document file on server', upload_to='', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='When was this document created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='e.g. 53.860421', max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='e.g. 10.713462', max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='birthday'),
        ),
    ]
