# Generated by Django 2.2.6 on 2019-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191018_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='picture',
            field=models.ImageField(blank=True, help_text='please provide a passport-style photo for the badge', upload_to='', verbose_name='badge photo'),
        ),
    ]
