# Generated by Django 2.2.6 on 2019-10-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191019_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganization',
            name='flag',
            field=models.FileField(blank=True, help_text='Flag of the Member Organization if it has one', upload_to='', verbose_name='Flag File'),
        ),
        migrations.AddField(
            model_name='school',
            name='comment',
            field=models.TextField(blank=True, help_text='Write down notes and comments regarding this school here, e.g. outstanding fees, contact persons names, etc.', verbose_name='Internal Comment'),
        ),
    ]
