# Generated by Django 2.2.6 on 2019-11-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191020_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Document file on server', upload_to='documents', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='picture',
            field=models.ImageField(blank=True, help_text='please provide a passport-style photo for the badge', upload_to='images/badge_photos', verbose_name='badge photo'),
        ),
    ]
