# Generated by Django 2.2.6 on 2019-11-03 21:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191103_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='availability',
            field=models.CharField(blank=True, help_text='Please specify on which days and nighs you will attend the conference and give your advice', max_length=512, null=True, verbose_name='Availability during week'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='experience',
            field=models.CharField(blank=True, help_text="Please specify which role you had in former MUNOL sessions and other conferences, e.g. 'School Management 2013'", max_length=512, null=True, verbose_name='MUN Experience'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='final_registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='final registration deadline'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='position_paper_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='position paper deadline'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='theme',
            field=models.CharField(blank=True, help_text='Overarching topic of the conference', max_length=100, null=True, verbose_name='conference theme'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, help_text='Who created this document?', max_length=100, null=True, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text="Specify the end time, none if it's open ended", null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.CharField(blank=True, help_text='Add additional information, e.g. dress code, speakers title', max_length=200, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='abbreviation',
            field=models.CharField(blank=True, help_text="e.g. 'GA1', 'ECOSOC'", max_length=10, null=True, verbose_name='Abbreviated Forum Name'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='email',
            field=models.EmailField(blank=True, help_text='Email will be displayed on website', max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='subtitle',
            field=models.CharField(blank=True, help_text="e.g. 'Disarmament and International Security", max_length=75, null=True, verbose_name='Explanatory Subtitle'),
        ),
        migrations.AlterField(
            model_name='memberorganization',
            name='flag',
            field=models.FileField(blank=True, help_text='Flag of the Member Organization if it has one', null=True, upload_to='', verbose_name='Flag File'),
        ),
        migrations.AlterField(
            model_name='mundirector',
            name='landline_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="in case that a call is quicker than an email, don't forget the country code", max_length=128, null=True, region=None, verbose_name='landline phone'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='extras',
            field=models.TextField(blank=True, help_text='please include here all additional information about diet, allergies, preferences etc. so that we can try to provide a perfect conference', null=True, verbose_name='extra information'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='remember to include the country code, e.g. for Germany +49 and then leave out the leading 0', max_length=128, null=True, region=None, verbose_name='mobile phone'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='picture',
            field=models.ImageField(blank=True, help_text='please provide a passport-style photo for the badge', null=True, upload_to='images/badge_photos', verbose_name='badge photo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='arrival',
            field=models.TextField(blank=True, help_text='Please provide date, time and location (e.g. school, conference venue, train station, airport, ...) of arrival here so that we can plan the registration process and housing respectively.', null=True, verbose_name='Arrival Information'),
        ),
        migrations.AlterField(
            model_name='school',
            name='comment',
            field=models.TextField(blank=True, help_text='Write down notes and comments regarding this school here, e.g. outstanding fees, contact persons names, etc.', null=True, verbose_name='Internal Comment'),
        ),
        migrations.AlterField(
            model_name='school',
            name='departure',
            field=models.TextField(blank=True, help_text='Please provide date, time and location (e.g. conference venue, train station, airport, ...) of departure here so that we can plan in advance.', null=True, verbose_name='Departure Information'),
        ),
    ]
