# Generated by Django 3.1.14 on 2022-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191103_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='lunches',
            field=models.ManyToManyField(blank=True, to='api.Lunch'),
        ),
        migrations.AlterField(
            model_name='memberorganization',
            name='flag',
            field=models.URLField(blank=True, help_text='URL to SVG Flag file of the Member Organization if it has one', max_length=250, null=True, verbose_name='Flag URL'),
        ),
    ]
