# Generated by Django 3.1.14 on 2022-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_school_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
    ]
