# Generated by Django 3.1.14 on 2023-11-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_school_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(help_text="e.g. 'Thomas-Mann-Straße 14', i.e. Street Name and House Number", max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='memberorganization',
            name='name',
            field=models.CharField(help_text="Use common (short) version of the name, e.g. 'Russia' instead of 'Russian Federation' or 'EU' instead of 'European Union', so use abbreviations. This name is only used internally and thus allows to create Countries twice, e.g. China 1 and China 2 if the delegation is split between two schools.", max_length=50, verbose_name="Member state's or Organization's name"),
        ),
        migrations.AlterField(
            model_name='memberorganization',
            name='official_name',
            field=models.CharField(help_text="Official name as stated on resolutions of the UN, e.g. 'Russian Federation' instead of Russia. No abbreviations allowed here.", max_length=150, verbose_name='Official Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country of origin'),
        ),
        migrations.AlterField(
            model_name='school',
            name='registration_status',
            field=models.CharField(choices=[('WAITING_FOR_PRE_REGISTRATION', 'waiting for pre-registration'), ('PRE_REGISTRATION_DONE', 'pre-registration done'), ('WAITING_FOR_DATA_PROTECTION', 'waiting for data protection'), ('WAITING_FOR_FINAL_REGISTRATION', 'waiting for final registration'), ('FINAL_REGISTRATION_DONE', 'final registration done'), ('CANCELED', 'canceled')], default='WAITING_FOR_PRE_REGISTRATION', help_text='This status indicates at what stage of registration the school is.', max_length=50, verbose_name='Registration status'),
        ),
        migrations.AlterField(
            model_name='school',
            name='requested',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note, that this is the <b>requested</b> number, <u>not</u> the confirmed one which might be lower.', null=True, verbose_name='Number of requested students'),
        ),
        migrations.AlterField(
            model_name='school',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code'),
        ),
    ]
