# Generated by Django 3.1.14 on 2023-05-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_app_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(blank=True, max_length=30, verbose_name='the position specific to their role'),
        ),
    ]
