# Generated by Django 3.1.14 on 2023-11-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20231114_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='housing',
        ),
        migrations.AddField(
            model_name='delegate',
            name='first_timer',
            field=models.BooleanField(default=True, help_text='There is a first MUN conference for everyone. Knowing this in advance, the team can prepare a smooth first conference for first timers.', verbose_name='It the delegate participating in their first MUN conference?'),
        ),
        migrations.AddField(
            model_name='school',
            name='housing_delegates',
            field=models.CharField(choices=[('hostel', 'hostel'), ('guest family', 'guest family'), ('other', 'other self-organized accommodation')], default='other', help_text='Please note, that housing in guest families is not available for all delegations and we will prefer international delegations in our housing who travel the longest distances.', max_length=50, verbose_name='Housing option for delegates'),
        ),
        migrations.AddField(
            model_name='school',
            name='housing_mun_directors',
            field=models.CharField(choices=[('hostel', 'hostel'), ('guest family', 'guest family'), ('other', 'other self-organized accommodation')], default='other', help_text='Please note, that housing in guest families is not available for all delegations and we will prefer international delegations in our housing who travels the longest distances.', max_length=50, verbose_name='Housing option for MUN-Directors'),
        ),
    ]
