# Generated by Django 3.1.14 on 2023-05-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_limitparticipantfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(help_text="e.g. 'First Committee', 'Economic and Social Council", max_length=60, verbose_name='Forum Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='the position specific to their role'),
        ),
    ]
