# Generated by Django 3.1.14 on 2024-03-11 15:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20231114_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mundirector',
            name='housing',
        ),
        migrations.AddField(
            model_name='event',
            name='relevance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('advisor', 'Conference Advisor'), ('chair', 'Chair'), ('delegate', 'Delegate'), ('mun_director', 'MUN Director'), ('executive', 'Executive'), ('staff', 'Staff')], max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(blank=True, choices=[('advisor', 'Conference Advisor'), ('chair', 'Chair'), ('delegate', 'Delegate'), ('mun_director', 'MUN Director'), ('executive', 'Executive'), ('staff', 'Staff')], max_length=12, verbose_name='the role they are participating in the conference as'),
        ),
    ]
