# Generated by Django 3.1.14 on 2024-03-11 15:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    replaces = [('api', '0032_event_relevance'), ('api', '0033_auto_20240311_1504')]

    dependencies = [
        ('api', '0031_auto_20230516_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='relevance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('advisor', 'Conference Advisor'), ('chair', 'Chair'), ('delegate', 'Delegate'), ('mun_director', 'MUN Director'), ('executive', 'Executive'), ('staff', 'Staff')], max_length=51, null=True),
        ),
    ]
