# Generated by Django 3.2.25 on 2024-05-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20240411_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plenary',
            name='name',
        ),
        migrations.AlterField(
            model_name='plenary',
            name='lunches',
            field=models.ManyToManyField(blank=True, to='api.Lunch'),
        ),
    ]
