# Generated by Django 3.2.25 on 2024-05-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20240507_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='chairhuman',
            new_name='chair_human',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='startdate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='vice_chairhuman',
            new_name='vice_chair_human',
        ),
        migrations.RemoveField(
            model_name='school',
            name='fee',
        ),
        migrations.AddField(
            model_name='participant',
            name='pronouns',
            field=models.CharField(blank=True, help_text="pronouns to be used to reference a person, e.g. 'she/her', 'he/him', 'they/them' or custom pronouns", max_length=50, null=True, verbose_name='pronouns'),
        ),
        migrations.AddField(
            model_name='school',
            name='fee_paid',
            field=models.BooleanField(default=False, help_text='Was the pre-registration fee paid?', verbose_name='Pre-registration fee paid'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='school',
            field=models.ForeignKey(blank=True, help_text='select the school which is attended by this delegate', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.school'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, help_text='Including second names if wanted', max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, help_text="Including prefixes like 'von', 'zu', 'de' etc.", max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='housing_delegates',
            field=models.CharField(blank=True, choices=[('hostel', 'hostel'), ('guest family', 'guest family'), ('other', 'other self-organized accommodation')], help_text='Please note, that housing in guest families is not available for all delegations and we will prefer international delegations in our housing who travel the longest distances.', max_length=50, verbose_name='Housing option for delegates'),
        ),
        migrations.AlterField(
            model_name='school',
            name='housing_mun_directors',
            field=models.CharField(blank=True, choices=[('hostel', 'hostel'), ('guest family', 'guest family'), ('other', 'other self-organized accommodation')], help_text='Please note, that housing in guest families is not available for all delegations and we will prefer international delegations in our housing who travels the longest distances.', max_length=50, verbose_name='Housing option for MUN-Directors'),
        ),
        migrations.AlterField(
            model_name='school',
            name='registration_status',
            field=models.CharField(choices=[('WAITING_FOR_PRE_REGISTRATION', 'waiting for pre-registration'), ('PRE_REGISTRATION_DONE', 'pre-registration done'), ('WAITING_FOR_FINAL_REGISTRATION', 'waiting for final registration'), ('FINAL_REGISTRATION_DONE', 'final registration done'), ('CANCELED', 'canceled')], default='WAITING_FOR_PRE_REGISTRATION', help_text='This status indicates at what stage of registration the school is.', max_length=50, verbose_name='Registration status'),
        ),
    ]
