# Generated by Django 3.2.25 on 2024-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_adjust_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='picture',
            field=models.TextField(blank=True, help_text='please provide a passport-style photo for the badge, base64 encoded', null=True, verbose_name='badge photo'),
        ),
    ]
