# Generated by Django 3.2.25 on 2024-06-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_badge_photo_as_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='help',
            field=models.CharField(blank=True, help_text='In which areas would you like to support the team?', max_length=512, null=True, verbose_name='Areas of help'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='department_name',
            field=models.CharField(blank=True, help_text="e.g. 'School Management', note that this name is <b>not</b> the entire position title. Some positions may not belong to a department.", max_length=50, null=True, verbose_name='Department name'),
        ),
    ]
