# Generated by Django 3.2.25 on 2024-08-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_removed_position_level_and_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='first_timer',
            field=models.BooleanField(default=True, help_text='There is a first MUN conference for everyone. Knowing this in advance, the team can prepare a smooth first conference for first timers.', verbose_name='Is the delegate participating in their first MUN conference?'),
        ),
    ]
