# Generated by Django 4.2.15 on 2024-10-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_delegate_first_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='data_consent_ip',
            field=models.GenericIPAddressField(blank=True, help_text='From which IP address did the participant give consent to store their data? Null if not given yet.', null=True, verbose_name='Data Consent given from IP'),
        ),
        migrations.AddField(
            model_name='participant',
            name='data_consent_time',
            field=models.DateTimeField(blank=True, help_text='When did the participant give consent to store their data? Null if not given yet.', null=True, verbose_name='Data Consent given at'),
        ),
        migrations.AddField(
            model_name='participant',
            name='media_consent_ip',
            field=models.GenericIPAddressField(blank=True, help_text='From which IP address did the participant give consent to use their media? Null if not given yet.', null=True, verbose_name='Media Consent given from IP'),
        ),
        migrations.AddField(
            model_name='participant',
            name='media_consent_time',
            field=models.DateTimeField(blank=True, help_text='When did the participant give consent to use their media? Null if not given yet.', null=True, verbose_name='Media Consent given at'),
        ),
    ]
