# Generated by Django 4.2.16 on 2025-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='picture',
            field=models.ImageField(blank=True, help_text='please provide a passport-style photo for the badge', null=True, upload_to='images/badge_photos', verbose_name='badge photo'),
        ),
    ]
