# Generated by Django 4.2.16 on 2025-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='app_code',
            field=models.CharField(blank=True, editable=False, help_text='auto-generated one time login code', max_length=8, verbose_name='app login code'),
        ),
        migrations.AddField(
            model_name='participant',
            name='app_code_expires_by',
            field=models.DateTimeField(blank=True, editable=False, help_text='expiration date for the app code', null=True, verbose_name='app code expires by'),
        ),
        migrations.AddField(
            model_name='participant',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='the position specific to their role'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other'), ('u', 'prefer not to say')], default='u', help_text="the diversity of genders is reflected in the 'other' choice", max_length=1, verbose_name='gender'),
        ),
    ]
