# Generated by Django 4.2.16 on 2025-04-18 23:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_participant_app_code_participant_app_code_expires_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='relevance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('advisor', 'Conference Advisor'), ('student officer', 'Student Officer'), ('delegate', 'Delegate'), ('mun_director', 'MUN Director'), ('executive', 'Executive'), ('staff', 'Staff')], default=[], max_length=61),
            preserve_default=False,
        ),
    ]
