# Generated by Django 4.2.16 on 2025-05-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_participant_picture'),
        ('api', '0043_alter_event_relevance'),
    ]

    operations = [
    ]
