# Generated by Django 4.2.16 on 2025-06-29 10:36

from django.db import migrations
from django.contrib.auth.models import User
from api.models import School

def assign_unique_users_to_schools(apps, schema_editor):
 
    for i, school in enumerate(School.objects.filter(user__isnull=True)):
        user = User.objects.create(username=f'school_user_{i}')
        school.user = user
        school.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_school_user'),
    ]

    operations = [
        migrations.RunPython(assign_unique_users_to_schools),
    ]
