# Generated by Django 4.2.16 on 2025-07-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User

def assign_users_to_participants(apps, schema_editor):
    Participant = apps.get_model('api', 'Participant')
    User = apps.get_model('auth', 'User')

    for participant in Participant.objects.all():
        if participant.user_id:
            continue

        user = User.objects.create(
            username=f"participant_{participant.pk}",
            email=participant.email or "",
            password='!'  # unusable password
        )

        participant.user_id = user.pk
        participant.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0045_alter_school_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_users_to_participants),
    ]
