# Generated by Django 4.2.16 on 2025-07-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_participant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, help_text="Please provide a valid email address, e.g. for passwordless authentication (needs to be unique). If you don't have one, leave it blank.", max_length=254, null=True, unique=True, verbose_name='E-Mail'),
        ),
    ]
