# Generated by Django 4.2.27 on 2026-01-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_participant_diet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='organizers_notice_ip',
            field=models.GenericIPAddressField(blank=True, help_text="From which IP address did the participant confirm that they've read the organizer's notice? Null if not confirmed yet.", null=True, verbose_name="Organizer's Notice confirmed from IP"),
        ),
        migrations.AddField(
            model_name='participant',
            name='organizers_notice_time',
            field=models.DateTimeField(blank=True, help_text="When did the participant confirm that they've read the organizer's notice? Null if not confirmed yet.", null=True, verbose_name="Organizer's Notice confirmed at"),
        ),
    ]
