# Generated by Django 4.2.30 on 2026-05-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_merge_20250510_1911'),
        ('api', '0050_participant_organizers_notice_ip_and_more'),
    ]

    operations = [
    ]
