# Generated by Django 4.2.30 on 2026-05-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_merge_20260510_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='position',
        ),
        migrations.AddField(
            model_name='participant',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Has the email address been verified?', verbose_name='E-Mail verified'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, help_text="Please provide a valid email address, e.g. for passwordless authentication (needs to be unique). If you don't have one, leave it blank.", max_length=254, null=True, unique=True, verbose_name='E-Mail'),
        ),
    ]
