# Generated by Django 4.2.30 on 2026-05-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_participant_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='app_code',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='app_code_expires_by',
        ),
        migrations.CreateModel(
            name='ParticipantLoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(blank=True, editable=False, help_text='auto-generated one time login code', max_length=8, verbose_name='app login code')),
                ('app_code_expires_by', models.DateTimeField(blank=True, editable=False, help_text='expiration date for the app code', null=True, verbose_name='app code expires by')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
            ],
        ),
    ]
