MIGRATE_TOKEN = ''
EMAIL_PASSWORD = ''
RSA_PASSPHRASE = b''
RSA_PRIVATE_KEY = b"""
-----BEGIN ENCRYPTED PRIVATE KEY-----
...
-----END ENCRYPTED PRIVATE KEY-----"""
RSA_PUBLIC_KEY = b"""
-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----"""